services:
  - type: web
    name: resume-ml-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host=0.0.0.0 --port=$PORT
    envVars:
      - key: JSEARCH_API_KEY
        sync: false  # Manually set in Render dashboard
