services:
  - type: web
    name: resume-ml-api
    env: python
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      pip install --no-cache-dir --extra-index-url https://download.pytorch.org/whl/cpu -r requirements.txt
    startCommand: uvicorn app:app --host=0.0.0.0 --port=$PORT
    envVars:
      - key: JSEARCH_API_KEY
        sync: false
